# Reference: Week6Session2 frontend-serviceNodePort.yaml

apiVersion: v1

kind: Service

metadata:
  name: webapp-service
  labels:
    app: employees

spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: employees