# Reference: Week6Session2 frontend-deplyoment.yaml

apiVersion: apps/v1

kind: Deployment

metadata:
  name: webapp-deplmnt
  labels:
    app: employees

spec:
  selector:
    matchLabels:
      app: employees
  replicas: 3
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp-deplmnt
        image: 697366856643.dkr.ecr.us-east-1.amazonaws.com/webapp-images:v0.2
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service.mysql.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: "pass123"