# Reference: https://kubernetes.io/docs/concepts/workloads/pods/
# Reference: https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/

apiVersion: v1

kind: Pod

metadata:
  name: webapp-pod
spec:
  containers:
  - name: webapp-pod
    image: 697366856643.dkr.ecr.us-east-1.amazonaws.com/webapp-images:v0.1
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: "mysql-service.mysql.svc.cluster.local"
    - name: DBPORT
      value: "3306"
    - name: DBPWD
      value: "pass123"